### ISSUE TITLE
Can't install with pip

### ISSUE THREAD

**Issue by jensfinnas** [26fe/jsonstat.py#2]
I'm trying to install jsonstat with `pip install jsonstat`, but getting the following error:

```
Could not find a version that satisfies the requirement jsonstat (from versions: )
No matching distribution found for jsonstat
```

Pip version is 8.1.2.

**Comment by ohenrik** [comment]
I seems like the real name of this package is `jsonstat.py` so you need to use pip install jsonstat.py.

**Comment by jensfinnas** [comment]
Thanks. I'm getting this error on `pip install jsonstat.py` though:

```
Downloading jsonstat.py-0.1.11.tar.gz
    Complete output from command python setup.py egg_info:
    error in jsonstat.py setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-LJ9Tfz/jsonstat.py/
```

**Comment by rotsee** [comment]
Same problem here, here's pip.log:

    Downloading jsonstat.py-0.1.11.tar.gz
    Downloading from URL https://pypi.python.org/packages/3d/ea/d3438fe2c0275e04ebba8e0562c8b1faa37a6f135d65d06aaeb50dce640c/jsonstat.py-0.1.11.tar.gz#md5=db8e06a011cbcf425d6938231db5361d (from https://pypi.python.org/simple/jsonstat.py/)
    Running setup.py (path:/tmp/pip_build_root/jsonstat.py/setup.py) egg_info for package jsonstat.py
      error in jsonstat.py setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
      Complete output from command python setup.py egg_info:
        error in jsonstat.py setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
    
    ----------------------------------------
    Cleaning up...
      Removing temporary dir /tmp/pip_build_root...
    Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/jsonstat.py
    Exception information:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
        status = self.run(options, args)
      File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
        requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
      File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1230, in prepare_files
        req_to_install.run_egg_info()
      File "/usr/lib/python2.7/dist-packages/pip/req.py", line 326, in run_egg_info
        command_desc='python setup.py egg_info')
      File "/usr/lib/python2.7/dist-packages/pip/util.py", line 715, in call_subprocess
    % (command_desc, proc.returncode, cwd))
    InstallationError: Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/jsonstat.py
